import { type IClientConfig, validate as validateClientConfig} from './configs/client/index.js'
import { type ISignerConfig, validate as validateSignerConfig } from './configs/signer/index.js'
import { type IGlobalConfig, validate as validateGlobalConfig } from './configs/global/index.js'
import { parseUserDefinedConfigFile, validateRequiredKeys } from './utils.js'
import { mkdirp } from 'mkdirp'
import type { IConfig } from './types.js'

enum ConfigNames {
  Global = 'global',
  Client = 'client',
  Signer = 'signer'
}

export interface ConfigInitOptions {
  configPath?: string
  dryRun?: boolean
  clientName?: string
}

/**
 * This class assumes that the user-defined config file contains an entry for every item, even if the
 * entry is an empty string. This is reasonable because the user-defined config file is generated by
 * the CLI and the CLI will always generate an entry for every item.
 *
 * Since there is no way to enforce that the user-defined config file contains an entry for every item
 * until runtime, this module contains checks to ensure that the user-defined config file contains an
 * entry for every item.
 */

export class Config {
  static #initialized: boolean = false
  static #globalConfig: IGlobalConfig
  static #clientConfig: IClientConfig
  static #signerConfig: ISignerConfig

  static async init (configPath?: string, dryRun?: boolean): Promise<void> {
    if (Config.#initialized) {
      throw new Error('Config already initialized')
    }

    const config: IConfig = await parseUserDefinedConfigFile(configPath)
    validateRequiredKeys<IConfig>(config, Object.values(ConfigNames))

    Config.#globalConfig = config[ConfigNames.Global]
    Config.#clientConfig = config[ConfigNames.Client]
    Config.#signerConfig = config[ConfigNames.Signer]

    // TODO: Better way to do this (and any CLI overrides in general)
    if (typeof config[ConfigNames.Global]?.options?.dryRun === 'undefined') {
      throw new Error('Config file must contain a dryRun option')
    }
    if (typeof config[ConfigNames.Global]?.options?.dbDir === 'undefined') {
      throw new Error('Config file must contain a dbDir option')
    }

    // TODO: Better way to do these
    // CLI options override config file
    if (typeof dryRun !== 'undefined') {
      Config.#globalConfig.options.dryRun = dryRun
    }
    // Create db dir if it doesn't exist
    mkdirp.sync(Config.#globalConfig.options.dbDir)

    Config.#initialized = true
  }

  // @dev validateConfig needs to be independent of init since it uses the configs for
  // validation (like in getRpcProvider). By keeping it separate, the scope will
  // close after init and all the configs will be available to use for validation.
  static async validateConfig (): Promise<void> {
    if (!Config.#initialized) {
      throw new Error('Config not ready for validation')
    }

    await validateGlobalConfig(Config.#globalConfig)
    await validateSignerConfig(Config.#signerConfig)
    await validateClientConfig(Config.#clientConfig)
  }


  // Expose individual configs
  static get GlobalConfig(): IGlobalConfig {
    if (!Config.#initialized) {
      throw new Error('GlobalConfig not yet initialized')
    }
    return Config.#globalConfig
  }

  static get ClientConfig(): IClientConfig {
    if (!Config.#initialized) {
      throw new Error('ClientConfig not yet initialized')
    }
    return Config.#clientConfig
  }

  static get SignerConfig(): ISignerConfig {
    if (!Config.#initialized) {
      throw new Error('SignerConfig already initialized')
    }
    return Config.#signerConfig
  }
}
