export {
  goerli, sepolia, mainnet,
  ChainSlug,
  AssetSymbol,
  FinalityState,
  Bps,
  Fees,
  RelayerFeeWei,
  RelayerFeeEnabled,
  BridgeDeprecated,
  TotalStake,
  DefaultSendGasLimit,
  Config,
  Chains,
  sdkMetadata as metadata,
  bondableChains,
  rateLimitMaxRetries,
  rpcTimeoutSeconds,
  sdkConfig as config
} from '@hop-protocol/sdk-core/config'
