packages:
  #- 'packages/*'
  - 'packages/api'
  - 'packages/explorer-backend'
  - 'packages/explorer-frontend'
  - 'packages/frontend'
  #- 'packages/hop-node'
  - 'packages/metabase'
  - 'packages/sdk'
  - 'packages/sdk-demo'
  - 'packages/stats-worker'
  - 'packages/v2-explorer-backend'
  - 'packages/v2-explorer-frontend'
  - 'packages/v2-hop-node'
  - 'packages/v2-sdk'
  - 'packages/v2-sdk-demo'
