/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { MockExecutor, MockExecutorInterface } from "../MockExecutor.js";

const _abi = [
  {
    type: "function",
    name: "execute",
    inputs: [
      {
        name: "messageId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "fromChainId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "from",
        type: "address",
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        internalType: "address",
      },
      {
        name: "data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "MessageIdExecuted",
    inputs: [
      {
        name: "fromChainId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "messageId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "MessageFailure",
    inputs: [
      {
        name: "messageId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "errorData",
        type: "bytes",
        internalType: "bytes",
      },
    ],
  },
  {
    type: "error",
    name: "MessageIdAlreadyExecuted",
    inputs: [
      {
        name: "messageId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
];

export class MockExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): MockExecutorInterface {
    return new utils.Interface(_abi) as MockExecutorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockExecutor {
    return new Contract(address, _abi, signerOrProvider) as MockExecutor;
  }
}
