export const pinataApiKey = process.env.PINATA_API_KEY
export const pinataSecretApiKey = process.env.PINATA_SECRET_API_KEY
export const awsAccessKeyId = process.env.AWS_ACCESS_KEY_ID
export const awsSecretAccessKey = process.env.AWS_SECRET_ACCESS_KEY
export const awsRegion = process.env.AWS_REGION
export const awsProfile = process.env.AWS_PROFILE
export const ethereumRpc = process.env.ETHEREUM_RPC
export const gnosisRpc = process.env.XDAI_RPC
export const polygonRpc = process.env.POLYGON_RPC
export const optimismRpc = process.env.OPTIMISM_RPC
export const arbitrumRpc = process.env.ARBITRUM_RPC
export const dbPath = process.env.SQLITE3_DB || './sqlite3.db'
