/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ArbERC20, ArbERC20Interface } from "../ArbERC20.js";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ArbERC20__factory {
  static readonly abi = _abi;
  static createInterface(): ArbERC20Interface {
    return new utils.Interface(_abi) as ArbERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ArbERC20 {
    return new Contract(address, _abi, signerOrProvider) as ArbERC20;
  }
}
