/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RailsPath } from "./RailsPath";
export * as factories from "./factories";
export { RailsPath__factory } from "./factories/RailsPath__factory";
