/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common.js";

export type HopStruct = {
  pathId: BytesLike;
  maxBonderFee: BigNumberish;
  maxTotalSent: BigNumberish;
  attestedClaimId: BytesLike;
};

export type HopStructOutput = [string, BigNumber, BigNumber, string] & {
  pathId: string;
  maxBonderFee: BigNumber;
  maxTotalSent: BigNumber;
  attestedClaimId: string;
};

export interface RailsGatewayInterface extends utils.Interface {
  functions: {
    "bond(bytes32,bytes32,uint256,(bytes32,uint256,uint256,bytes32)[])": FunctionFragment;
    "claimFeesFromPath(bytes32)": FunctionFragment;
    "confirmClaim(bytes32,bytes32)": FunctionFragment;
    "counterpartChainIds(bytes32)": FunctionFragment;
    "defaultTokenFee()": FunctionFragment;
    "dispatcher()": FunctionFragment;
    "distributeClaimedFees(bytes32,address,uint256,bytes32)": FunctionFragment;
    "executor()": FunctionFragment;
    "feeManager()": FunctionFragment;
    "gateways(uint256)": FunctionFragment;
    "getAmountOut(bytes32,uint256,bytes32,uint256)": FunctionFragment;
    "getCounterpartChainId(bytes32)": FunctionFragment;
    "getMessageFee(uint256)": FunctionFragment;
    "getPath(bytes32)": FunctionFragment;
    "getPathId(uint256,address,uint256,address,uint256)": FunctionFragment;
    "getPushClaimFee()": FunctionFragment;
    "getRemoveFee()": FunctionFragment;
    "getSendFee(bytes32)": FunctionFragment;
    "initChain(uint256,address)": FunctionFragment;
    "initPath(address,uint256,address,uint256)": FunctionFragment;
    "isPathInitialized(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "pushClaim(bytes32,bytes32,address,uint256,uint256,bytes32,uint256,bytes32)": FunctionFragment;
    "pushClaimAndBond(bytes32,bytes32,address,uint256,uint256,bytes32,uint256,uint256,(bytes32,uint256,uint256,bytes32)[])": FunctionFragment;
    "pushClaimAndWithdraw(bytes32,bytes32,address,uint256,uint256,bytes32,uint256,(bytes32,uint256,uint256,bytes32)[])": FunctionFragment;
    "railsPathImplementation()": FunctionFragment;
    "readdClaim(bytes32,bytes32,bytes32)": FunctionFragment;
    "removeClaim(bytes32,bytes32)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "send(address,uint256,(bytes32,uint256,uint256,bytes32)[])": FunctionFragment;
    "setDefaultTokenFee(uint256)": FunctionFragment;
    "setStakingRegistry(address)": FunctionFragment;
    "setTokenFeeRecipient(address)": FunctionFragment;
    "stakingRegistry()": FunctionFragment;
    "tokens(bytes32)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateDefaultTokenFee(uint256)": FunctionFragment;
    "updateTokenFee(bytes32,uint256)": FunctionFragment;
    "withdrawBonds(bytes32,bytes32)": FunctionFragment;
    "withdrawClaim(bytes32,bytes32,(bytes32,uint256,uint256,bytes32)[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bond"
      | "claimFeesFromPath"
      | "confirmClaim"
      | "counterpartChainIds"
      | "defaultTokenFee"
      | "dispatcher"
      | "distributeClaimedFees"
      | "executor"
      | "feeManager"
      | "gateways"
      | "getAmountOut"
      | "getCounterpartChainId"
      | "getMessageFee"
      | "getPath"
      | "getPathId"
      | "getPushClaimFee"
      | "getRemoveFee"
      | "getSendFee"
      | "initChain"
      | "initPath"
      | "isPathInitialized"
      | "owner"
      | "pushClaim"
      | "pushClaimAndBond"
      | "pushClaimAndWithdraw"
      | "railsPathImplementation"
      | "readdClaim"
      | "removeClaim"
      | "renounceOwnership"
      | "send"
      | "setDefaultTokenFee"
      | "setStakingRegistry"
      | "setTokenFeeRecipient"
      | "stakingRegistry"
      | "tokens"
      | "transferOwnership"
      | "updateDefaultTokenFee"
      | "updateTokenFee"
      | "withdrawBonds"
      | "withdrawClaim"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bond",
    values: [BytesLike, BytesLike, BigNumberish, HopStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFeesFromPath",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmClaim",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "counterpartChainIds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultTokenFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dispatcher",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeClaimedFees",
    values: [BytesLike, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "executor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gateways",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [BytesLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCounterpartChainId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPath", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPathId",
    values: [BigNumberish, string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPushClaimFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemoveFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSendFee",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initChain",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initPath",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPathInitialized",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pushClaim",
    values: [
      BytesLike,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pushClaimAndBond",
    values: [
      BytesLike,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      HopStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pushClaimAndWithdraw",
    values: [
      BytesLike,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      HopStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "railsPathImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "readdClaim",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeClaim",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [string, BigNumberish, HopStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultTokenFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenFeeRecipient",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tokens", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDefaultTokenFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTokenFee",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBonds",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawClaim",
    values: [BytesLike, BytesLike, HopStruct[]]
  ): string;

  decodeFunctionResult(functionFragment: "bond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimFeesFromPath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "counterpartChainIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultTokenFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dispatcher", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeClaimedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gateways", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCounterpartChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPath", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPathId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPushClaimFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemoveFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSendFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initChain", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initPath", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPathInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pushClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pushClaimAndBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushClaimAndWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "railsPathImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "readdClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultTokenFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDefaultTokenFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTokenFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBonds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawClaim",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "PathInitialized(bytes32,address,uint256,address,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PathInitialized"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PathInitializedEventObject {
  pathId: string;
  token: string;
  counterpartChainId: BigNumber;
  counterpartToken: string;
  initialReserve: BigNumber;
  path: string;
}
export type PathInitializedEvent = TypedEvent<
  [string, string, BigNumber, string, BigNumber, string],
  PathInitializedEventObject
>;

export type PathInitializedEventFilter = TypedEventFilter<PathInitializedEvent>;

export interface RailsGateway extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RailsGatewayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bond(
      pathId: BytesLike,
      claimId: BytesLike,
      bonderFee: BigNumberish,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimFeesFromPath(
      pathId: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    confirmClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    counterpartChainIds(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    defaultTokenFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    dispatcher(overrides?: CallOverrides): Promise<[string]>;

    distributeClaimedFees(
      pathId: BytesLike,
      account: string,
      totalFees: BigNumberish,
      lastClaimId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    executor(overrides?: CallOverrides): Promise<[string]>;

    feeManager(overrides?: CallOverrides): Promise<[string]>;

    gateways(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    getAmountOut(
      pathId: BytesLike,
      amount: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    getCounterpartChainId(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { counterpartChainId: BigNumber }>;

    getMessageFee(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { messageFee: BigNumber }>;

    getPath(pathId: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getPathId(
      chainId0: BigNumberish,
      token0: string,
      chainId1: BigNumberish,
      token1: string,
      initialReserve: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPushClaimFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRemoveFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSendFee(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    initChain(
      chainId: BigNumberish,
      gateway: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    initPath(
      token: string,
      counterpartChainId: BigNumberish,
      counterpartToken: string,
      initialReserve: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isPathInitialized(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pushClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amount: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      nextHopsHash: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    pushClaimAndBond(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amountOut: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      bonderFee: BigNumberish,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    pushClaimAndWithdraw(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amountOut: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    railsPathImplementation(overrides?: CallOverrides): Promise<[string]>;

    readdClaim(
      pathId: BytesLike,
      transferDataHash: BytesLike,
      claimId: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    removeClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    send(
      to: string,
      amount: BigNumberish,
      hops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    setDefaultTokenFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setStakingRegistry(
      newStakingRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setTokenFeeRecipient(
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    stakingRegistry(overrides?: CallOverrides): Promise<[string]>;

    tokens(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateDefaultTokenFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateTokenFee(
      pathId: BytesLike,
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawBonds(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  bond(
    pathId: BytesLike,
    claimId: BytesLike,
    bonderFee: BigNumberish,
    nextHops: HopStruct[],
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimFeesFromPath(
    pathId: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  confirmClaim(
    pathId: BytesLike,
    claimId: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  counterpartChainIds(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  defaultTokenFee(overrides?: CallOverrides): Promise<BigNumber>;

  dispatcher(overrides?: CallOverrides): Promise<string>;

  distributeClaimedFees(
    pathId: BytesLike,
    account: string,
    totalFees: BigNumberish,
    lastClaimId: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  executor(overrides?: CallOverrides): Promise<string>;

  feeManager(overrides?: CallOverrides): Promise<string>;

  gateways(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getAmountOut(
    pathId: BytesLike,
    amount: BigNumberish,
    attestedClaimId: BytesLike,
    sourcePool: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCounterpartChainId(
    pathId: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMessageFee(
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPath(pathId: BytesLike, overrides?: CallOverrides): Promise<string>;

  getPathId(
    chainId0: BigNumberish,
    token0: string,
    chainId1: BigNumberish,
    token1: string,
    initialReserve: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getPushClaimFee(overrides?: CallOverrides): Promise<BigNumber>;

  getRemoveFee(overrides?: CallOverrides): Promise<BigNumber>;

  getSendFee(pathId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  initChain(
    chainId: BigNumberish,
    gateway: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  initPath(
    token: string,
    counterpartChainId: BigNumberish,
    counterpartToken: string,
    initialReserve: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isPathInitialized(
    pathId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pushClaim(
    pathId: BytesLike,
    claimId: BytesLike,
    to: string,
    amount: BigNumberish,
    maxBonderFee: BigNumberish,
    attestedClaimId: BytesLike,
    sourcePool: BigNumberish,
    nextHopsHash: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  pushClaimAndBond(
    pathId: BytesLike,
    claimId: BytesLike,
    to: string,
    amountOut: BigNumberish,
    maxBonderFee: BigNumberish,
    attestedClaimId: BytesLike,
    sourcePool: BigNumberish,
    bonderFee: BigNumberish,
    nextHops: HopStruct[],
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  pushClaimAndWithdraw(
    pathId: BytesLike,
    claimId: BytesLike,
    to: string,
    amountOut: BigNumberish,
    maxBonderFee: BigNumberish,
    attestedClaimId: BytesLike,
    sourcePool: BigNumberish,
    nextHops: HopStruct[],
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  railsPathImplementation(overrides?: CallOverrides): Promise<string>;

  readdClaim(
    pathId: BytesLike,
    transferDataHash: BytesLike,
    claimId: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  removeClaim(
    pathId: BytesLike,
    claimId: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  send(
    to: string,
    amount: BigNumberish,
    hops: HopStruct[],
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  setDefaultTokenFee(
    fee: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setStakingRegistry(
    newStakingRegistry: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setTokenFeeRecipient(
    recipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  stakingRegistry(overrides?: CallOverrides): Promise<string>;

  tokens(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateDefaultTokenFee(
    fee: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateTokenFee(
    pathId: BytesLike,
    fee: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawBonds(
    pathId: BytesLike,
    claimId: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawClaim(
    pathId: BytesLike,
    claimId: BytesLike,
    nextHops: HopStruct[],
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    bond(
      pathId: BytesLike,
      claimId: BytesLike,
      bonderFee: BigNumberish,
      nextHops: HopStruct[],
      overrides?: CallOverrides
    ): Promise<string>;

    claimFeesFromPath(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    confirmClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    counterpartChainIds(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    defaultTokenFee(overrides?: CallOverrides): Promise<BigNumber>;

    dispatcher(overrides?: CallOverrides): Promise<string>;

    distributeClaimedFees(
      pathId: BytesLike,
      account: string,
      totalFees: BigNumberish,
      lastClaimId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    executor(overrides?: CallOverrides): Promise<string>;

    feeManager(overrides?: CallOverrides): Promise<string>;

    gateways(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    getAmountOut(
      pathId: BytesLike,
      amount: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCounterpartChainId(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMessageFee(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPath(pathId: BytesLike, overrides?: CallOverrides): Promise<string>;

    getPathId(
      chainId0: BigNumberish,
      token0: string,
      chainId1: BigNumberish,
      token1: string,
      initialReserve: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getPushClaimFee(overrides?: CallOverrides): Promise<BigNumber>;

    getRemoveFee(overrides?: CallOverrides): Promise<BigNumber>;

    getSendFee(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initChain(
      chainId: BigNumberish,
      gateway: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initPath(
      token: string,
      counterpartChainId: BigNumberish,
      counterpartToken: string,
      initialReserve: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isPathInitialized(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pushClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amount: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      nextHopsHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    pushClaimAndBond(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amountOut: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      bonderFee: BigNumberish,
      nextHops: HopStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    pushClaimAndWithdraw(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amountOut: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      nextHops: HopStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    railsPathImplementation(overrides?: CallOverrides): Promise<string>;

    readdClaim(
      pathId: BytesLike,
      transferDataHash: BytesLike,
      claimId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    removeClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    send(
      to: string,
      amount: BigNumberish,
      hops: HopStruct[],
      overrides?: CallOverrides
    ): Promise<string>;

    setDefaultTokenFee(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setStakingRegistry(
      newStakingRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenFeeRecipient(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    stakingRegistry(overrides?: CallOverrides): Promise<string>;

    tokens(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDefaultTokenFee(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTokenFee(
      pathId: BytesLike,
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawBonds(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      nextHops: HopStruct[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PathInitialized(bytes32,address,uint256,address,uint256,address)"(
      pathId?: null,
      token?: null,
      counterpartChainId?: null,
      counterpartToken?: null,
      initialReserve?: null,
      path?: null
    ): PathInitializedEventFilter;
    PathInitialized(
      pathId?: null,
      token?: null,
      counterpartChainId?: null,
      counterpartToken?: null,
      initialReserve?: null,
      path?: null
    ): PathInitializedEventFilter;
  };

  estimateGas: {
    bond(
      pathId: BytesLike,
      claimId: BytesLike,
      bonderFee: BigNumberish,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    claimFeesFromPath(
      pathId: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    confirmClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    counterpartChainIds(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    defaultTokenFee(overrides?: CallOverrides): Promise<BigNumber>;

    dispatcher(overrides?: CallOverrides): Promise<BigNumber>;

    distributeClaimedFees(
      pathId: BytesLike,
      account: string,
      totalFees: BigNumberish,
      lastClaimId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    executor(overrides?: CallOverrides): Promise<BigNumber>;

    feeManager(overrides?: CallOverrides): Promise<BigNumber>;

    gateways(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getAmountOut(
      pathId: BytesLike,
      amount: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCounterpartChainId(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMessageFee(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPath(pathId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getPathId(
      chainId0: BigNumberish,
      token0: string,
      chainId1: BigNumberish,
      token1: string,
      initialReserve: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPushClaimFee(overrides?: CallOverrides): Promise<BigNumber>;

    getRemoveFee(overrides?: CallOverrides): Promise<BigNumber>;

    getSendFee(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initChain(
      chainId: BigNumberish,
      gateway: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    initPath(
      token: string,
      counterpartChainId: BigNumberish,
      counterpartToken: string,
      initialReserve: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isPathInitialized(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pushClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amount: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      nextHopsHash: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    pushClaimAndBond(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amountOut: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      bonderFee: BigNumberish,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    pushClaimAndWithdraw(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amountOut: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    railsPathImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    readdClaim(
      pathId: BytesLike,
      transferDataHash: BytesLike,
      claimId: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    removeClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    send(
      to: string,
      amount: BigNumberish,
      hops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    setDefaultTokenFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setStakingRegistry(
      newStakingRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setTokenFeeRecipient(
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    stakingRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateDefaultTokenFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateTokenFee(
      pathId: BytesLike,
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawBonds(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bond(
      pathId: BytesLike,
      claimId: BytesLike,
      bonderFee: BigNumberish,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimFeesFromPath(
      pathId: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    confirmClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    counterpartChainIds(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    defaultTokenFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dispatcher(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    distributeClaimedFees(
      pathId: BytesLike,
      account: string,
      totalFees: BigNumberish,
      lastClaimId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    executor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gateways(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAmountOut(
      pathId: BytesLike,
      amount: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCounterpartChainId(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMessageFee(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPath(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPathId(
      chainId0: BigNumberish,
      token0: string,
      chainId1: BigNumberish,
      token1: string,
      initialReserve: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPushClaimFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRemoveFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSendFee(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initChain(
      chainId: BigNumberish,
      gateway: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    initPath(
      token: string,
      counterpartChainId: BigNumberish,
      counterpartToken: string,
      initialReserve: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isPathInitialized(
      pathId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pushClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amount: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      nextHopsHash: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    pushClaimAndBond(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amountOut: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      bonderFee: BigNumberish,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    pushClaimAndWithdraw(
      pathId: BytesLike,
      claimId: BytesLike,
      to: string,
      amountOut: BigNumberish,
      maxBonderFee: BigNumberish,
      attestedClaimId: BytesLike,
      sourcePool: BigNumberish,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    railsPathImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    readdClaim(
      pathId: BytesLike,
      transferDataHash: BytesLike,
      claimId: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    removeClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    send(
      to: string,
      amount: BigNumberish,
      hops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setDefaultTokenFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setStakingRegistry(
      newStakingRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setTokenFeeRecipient(
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    stakingRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokens(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateDefaultTokenFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateTokenFee(
      pathId: BytesLike,
      fee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawBonds(
      pathId: BytesLike,
      claimId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawClaim(
      pathId: BytesLike,
      claimId: BytesLike,
      nextHops: HopStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
